TITLE: My mega zuper nice blog
URL: www.url.com
DESCRIPTION: This is a blog about so many things and more
LANG: EN
STYLE: 'serif-and-sans'
AUTHOR: John Doe
CONTACT: true
EMAIL: johndoe@contact.com
POST_COVER: true
POST_THUMBNAILS: true
POST_SUGGESTIONS: true
HOME_NB_POSTS: 6
MENU:
  - label: RSS
    url: /rss.xms
  - label: Google
    url: http://www.google.com
