TITLE: Open Blog Revolution
URL: 'https://open-blog-revolution.netlify.app/'
BASE: ''
DESCRIPTION: Free blog template
LANG: EN
STYLE: sans
AUTHOR: Iko
CONTACT: true #Set to false to omit email/contact link in header
EMAIL: youremail@email.com
POST_COVER: true
# MY_SWITCH: true #uncomment to add additional link to header.
# MY_LINK: https://link.to.something #copy structure for further links.
# Edit also relevant parts in 'src/types/config.d.ts' and 'src/components/header.astro'.
POST_THUMBNAILS: true
POST_SUGGESTIONS: true
HOME_NB_POSTS: 6
MENU:
  - label: RSS
    url: rss.xml
  - label: Archive
    url: archive
  - label: Blogroll
    url: blogroll
BLOG_COVER:
  src: obr_large.png
  alt: Open Blog Revolution
BANNER:
  src: obr_banner.png
  alt: Open Blog Revolution Banner