TITLE: Open Blog Revolution
URL: www.url.com
DESCRIPTION: Free blog template, to be released soon
LANG: EN
STYLE: sans
AUTHOR: John Doe
CONTACT: true
EMAIL: johndoe@contact.com
POST_COVER: true
POST_THUMBNAILS: true
POST_SUGGESTIONS: true
HOME_NB_POSTS: 6
MENU:
  - label: RSS
    url: /rss.xml
  - label: Archive
    url: /archive/1
