TITLE: Open Blog Revolution
URL: https://tct-ab2.netlify.app/
DESCRIPTION: Free blog template
LANG: EN
STYLE: sans
AUTHOR: Iko
CONTACT: true
EMAIL: iko@thecodedtype.com
POST_COVER: true
POST_THUMBNAILS: true
POST_SUGGESTIONS: true
HOME_NB_POSTS: 6
MENU:
  - label: RSS
    url: /rss.xml
  - label: Archive
    url: /archive/1
BLOG_COVER:
  src: ../media/obr_large.png
  alt: Open Blog Revolution
